---
title: "Data Sources and Cleaning"
output: 
  html_document:
    toc: true
    toc_float: true
    code folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
source(here("source", "load_clean_brfss.R"))
brfss_data = load_clean_brfss(here("data", "brfss_clean_2017_2024.csv.zip"))
```

Our analysis relies on combining public health surveillance data with external information about trends in sports gambling.

# Data Sources and Scope

Our project utilizes two main sources spanning the period **2017 through 2024**:

* **Primary Source (Health Outcome / Demographic Data): The Behavioral Risk Factor Surveillance System (BRFSS)**. This is an annual, state-based, nationwide telephone survey (conducted by the CDC)[https://www.cdc.gov/brfss/index.html], providing detailed self-reported health and behavioral data. We analyzed **`r round(nrow(brfss_data)/1000000, digits = 2)` million** completed interviews across all available years. We chose this period as it spans the period before the **2018 Supreme Court ruling (PASPA repeal)**, which allowed many states to legalize sports betting.

* **Secondary Sources (Sports Gambling Policy and Market Activity Data)**: We used data scraped from [Legal Sports Report](https://www.legalsportsreport.com/sports-betting-states/revenue/) for market handle and manually compiled state legalization dates from the [American Gaming Association](https://www.americangaming.org/research/state-of-play-map/). 

# Data Cleaning and Processing

Due to variations in the BRFSS survey over the years, we standardized the data. This process was handled by a dedicated `source/` code folder, with the following functions ensuring data quality and analytical readiness:

  * **Variable Standardization**[standardize_brfss_variable.R](https://github.com/shivalikachavan/p8105_final/blob/main/source/standardize_brfss_variable.R): This function renames variables that have more than one version of the same variable (e.g. `HLTHPL1` and `HLTHPL2`). Seeing that the variables differed in name only (the responses were coded in the same way), this was handled by renaming different versions to the single standardized name. (e.g. `hlthpl_standard`). 
  * **Filtering** [filter_brfss_data.R](https://github.com/shivalikachavan/p8105_final/blob/main/source/filter_brfss_data.R): This function keeps the key variables for our study (unique survey identifiers, demographic/predictor variables, health/financial outcomes variables). It also filters for completed interviews (`dispcode = 1100`) and converts the date of the interview to a Date type variable. 
  * **Loading** [load_clean_brfss_data.R](https://github.com/shivalikachavan/p8105_final/blob/main/source/load_clean_brfss.R): This function is used to load the cleaned data set into R by recoding variables (e.g. `1 ~ "Male"`), and connects the date of each interview to the status of legalization in that state. This `sb_legal` treatment variable is added by merging with [state_legalization_dates.csv](https://github.com/shivalikachavan/p8105_final/blob/main/data/legal_sports_report/state_legalization_dates.csv).

# Analysis Data Dictionary

Our analysis focuses on the following treatment variable (exposure), outcome variables (adverse health indicator), and demographic variables. 

## Treatment Variable (Exposure)

* `sb_legal`: A binary flag indicating whether the interview took place **after** sports betting was legalized in that state ($\text{1}$) or before ($\text{0}$).

## Outcome Variables (Adverse Health)

We primarily use binary (Yes/No) measures to capture the prevalence of these adverse health outcomes in the population:

  * *At least 1 poor mental health day*: 
    * Survey Question: *"Now thinking about your mental health, which includes stress, depression, and problems with emotions, for how many days during the past 30 days was your mental health not good?"* 
    * If the respondent reported 1+ to this question, `any_mental_health_not_good_days` is `TRUE`. 
  * *At least 1 poor physical health day*: 
    * Survey Question: *"Now thinking about your physical health, which includes physical illness and injury, for how many days during the past 30 days was your physical health not good?"*
    * If the respondent reported 1+ to this question, `any_physical_health_not_good_days` is `TRUE`. 
  * *Depression*: 
    * Survey Question: *"Has a doctor or other health professional ever told you that you had a depressive disorder, including depression, major depression, dysthymia, or minor depression?"*
    * If the respondent reported "Yes" to this question, `has_depressive_disorder` is `TRUE`. 
  * *Binge Drinking:* 
    * Survey Question: *"Considering all alcoholic beverages that you drink, on average, how many times per month do you have 5 (for men) or 4 (for women) or more drinks on one occasion?"*
    * If the respondent reported "Yes" to this question, `has_binge_drink` is `TRUE`. 

## Demographic Variables

To control for social and economic factors influencing health, we include individual-level demographic predictors (e.g., sex, age group, income level, education, and employment status) in our regression models. These are important in our regression models. 